# Generated by Django 5.2.7 on 2025-10-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polloption',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
