# Generated by Django 5.2.7 on 2025-10-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_polloption_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='expected_turnout',
            field=models.PositiveIntegerField(blank=True, help_text='Очікуваний корпус виборців (шт.).', null=True),
        ),
    ]
