# Generated by Django 5.2.7 on 2025-11-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll_expected_turnout'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Якщо увімкнено, у MongoDB не зберігається справжній ID користувача, а результати по варіантах приховані до завершення.', verbose_name='Анонімне голосування'),
        ),
    ]
